### ISSUE TITLE
/lift reload Command

### ISSUE THREAD

**Issue by trainphreak** [croxis/Lift#135]
Proper reloading of the config would be awesome. Currently, changes can only be made to the config while the server is not running, even if using a plugin manager to disable/enable Lift.

**Comment by croxis** [comment]
Yah it was a situation I never was able to solve, I'm not sure what changes
happen to the entity so I'm not sure how to manage it. I haven't touched
the code in a while and I probably wont be able to get to it until spring
break (joys of being a teacher)

On Sun, Feb 28, 2016 at 1:04 PM, trainphreak <notifications@github.com>
wrote:

> Proper reloading of the config would be awesome. Currently, changes can
> only be made to the config while the server is not running, even if using a
> plugin manager to disable/enable Lift.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/croxis/Lift/issues/135>.
>



-- 
- David - Proud to be saving the world since 1984
