### ISSUE TITLE
Does the Scroll Feature exist in 1.16.2 Paper`?

### ISSUE THREAD

**Issue by CloudeLecaw** [croxis/Lift#186]
> Bug fixes
> Thanks to kikelkik for the code!
> 
> scrollable floor selection disables if player distance to the sign is more than 3 blocks
> scrollable floor selection disables if player is going up/down the Lift
> messages are send when scroll select is enabled/disabled as player feedback
> allow destroying signs (since the new scroll system, the event was being cancelled which prevents destroying a lift sign)...
> croxis, Monday at 9:44 PMReport... Read MoreLike
> kikelkik, starnos and TheoRetisch like this.
> Easy floor selection!
> Version 65:
> New feature! When you click on a sign with an empty hand, you use the mouse wheel to select the desired floor. Clicking again locks the sign.
> Clicking on a sign with an object in your hand will select the floor one at a time.
> Compiled for 1.16.1. Use with older versions at your own risk.
> Bugs: Plugin version string is at 64.

i tried Versopm 66 
We have no clue how to use the clickable thing with the weel.
If we punch the signs with empty hand left or right then it just changes the floor.
Not able to scroll the floors.
Also we see no measge in config or in the chat.

So we are not sure if this scrolling does really exists? And if it does...how is it actived//deatived for others/plaers

**Comment by kikelkik** [comment]
I think you might have got the wrong plugin version.
If you downloaded it from [spigot|https://www.spigotmc.org/resources/lift.4704/updates], you got version 63 for MC 1.15 (take a look at the plugin.yml), because @croxis must have mixed up his files a bit.
On [bukkit|https://dev.bukkit.org/projects/lift/files] there's the right version (66).

But due to a recent bug that can lead to TPS loss I would recommend you to wait for version 67 with that bugfix I made a [PR|https://github.com/croxis/Lift/pull/188] for.

**Comment by CloudeLecaw** [comment]
your right i also was wondering why on console it was called version 63.. i thought this was a  issue of the dev that just forgot to change it in plugin.yml^^

Thanks for this info

**Comment by croxis** [comment]
...yah it was me. Fixed!
